<a href="https://colab.research.google.com/github/sanketh96/Chatbot-2.0/blob/master/ProcessingNER2014.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

In [0]:
data = pd.read_csv('https://raw.githubusercontent.com/sanketh96/Datasets-for-Colab-25MB-/master/ner2014.csv?token=AOeG7pvWgAYmN7vjQH2WkuLjN0Az5D-Wks5ch5R8wA%3D%3D')

In [0]:
data.head()

   Unnamed: 0  POS  sentence_id  tag1 tag2 tag3 tag4  word
0           0  NNP            0  B-NP    o    o    o   URL
1           1    :            0     o    o    o    o     ;
2           2   NN            0  B-NP    o    o    o  http
3           3    :            0     o    o    o    o     :
4           4  SYM            0  B-NP    o    o    o     /

In [0]:
data.drop(columns=['Unnamed: 0'])

       POS  sentence_id    tag1      tag2 tag3 tag4                  word
0      NNP            0    B-NP         o    o    o                   URL
1        :            0       o         o    o    o                     ;
2       NN            0    B-NP         o    o    o                  http
3        :            0       o         o    o    o                     :
4      SYM            0    B-NP         o    o    o                     /
5      SYM            0    I-NP         o    o    o                     /
6       JJ            0    I-NP         o    o    o  www.indiapost.gov.in
7      SYM            0    I-NP         o    o    o                     /
8      NNP            0    I-NP         o    o    o              NSC.aspx
9      NNP            0    I-NP         o    o    o                  Time
10       :            0       o         o    o    o                     :
11      CD            0    B-NP         o    o    o                     3
12       .            0       o         o    o    o                     .
13      CD            1    B-NP         o    o    o                    30
14     NNP            1    I-NP         o    o    o                   P.M
15     NNP            1    I-NP         o    o    o              National
16     NNP            1    I-NP         o    o    o               Savings
17     NNS            1    I-NP         o    o    o          Certificates
18       (            1       o         o    o    o                     (
19     NNP            1    B-NP         o    o    o                   NSC
20     SYM            1    I-NP         o    o    o                     )
21     NNP            2    B-NP         o    o    o                   NSC
22     NNP            2    I-NP         o    o    o                  VIII
23      NN            2    I-NP         o    o    o                 Issue
24     SYM            3       o         o    o    o                     *
25     NNP            3    B-NP         o    o    o                Scheme
26      RB            3  B-ADVP         o    o    o             specially
27     VBD            3    B-VP         o    o    o              designed
28      IN            3    B-PP         o    o    o                   for
29     NNP            3    B-NP   B-GROUP    o    o            Government
...    ...          ...     ...       ...  ...  ...                   ...
86604   NN         3369    I-NP         o    o    o                 state
86605  NNS         3369    I-NP         o    o    o               remains
86606    .         3369       o         o    o    o                     .
86607   DT         3370    B-NP         o    o    o                   The
86608   JJ         3370    I-NP         o    o    o                 final
86609   NN         3370    I-NP         o    o    o                figure
86610   MD         3370    B-VP         o    o    o                  will
86611   VB         3370    I-VP         o    o    o                  come
86612   IN         3370    B-PP         o    o    o                  from
86613   DT         3370    B-NP         o    o    o                   the
86614  VBG         3370    I-NP         o    o    o             returning
86615   NN         3370    I-NP         o    o    o               officer
86616    .         3370       o         o    o    o                     .
86617  PRP         3371    B-NP         o    o    o                     I
86618   MD         3371    B-VP         o    o    o                 would
86619   VB         3371    I-VP         o    o    o                  like
86620   TO         3371    I-VP         o    o    o                    to
86621   VB         3371    I-VP         o    o    o                 thank
86622   DT         3371    B-NP         o    o    o                   the
86623  NNS         3371    I-NP         o    o    o                people
86624   IN         3371    B-PP         o    o    o                    of
86625  NNP         3371    B-NP  B-NATION    o    o                 India
86626   IN         3371    B-PP         o    o    o                   for
86627  VBG         3371    B-VP         o    o    o              electing
86628  PRP         3371    B-NP         o    o    o                    me
86629   TO         3371    B-PP         o    o    o                    to
86630   DT         3371    B-NP         o    o    o                  this
86631   JJ         3371    I-NP         o    o    o                  high
86632   NN         3371    I-NP         o    o    o                office
86633    .         3371       o         o    o    o                     .

[86634 rows x 7 columns]

In [0]:
tag2_list = data['tag2'].value_counts()
tag3_list = data['tag3'].value_counts()
tag4_list = data['tag4'].value_counts()

In [0]:
for tag in set(tag2_list.keys()).intersection(set(tag3_list.keys())):
  print("Tag : ", tag)
  print("-------")
  print("tag2 count : ", tag2_list[tag])
  print("tag3 count : ", tag3_list[tag])
  print()

Tag :  B-LOCOMOTIVE
-------
tag2 count :  23
tag3 count :  1

Tag :  B-TITLE
-------
tag2 count :  12
tag3 count :  198

Tag :  B-SPORTS
-------
tag2 count :  35
tag3 count :  19

Tag :  B-CHEMICAL
-------
tag2 count :  8
tag3 count :  1

Tag :  B-FAMILYNAME
-------
tag2 count :  2
tag3 count :  46

Tag :  B-PARK
-------
tag2 count :  3
tag3 count :  1

Tag :  I-LOCATION
-------
tag2 count :  6
tag3 count :  1

Tag :  I-ORGANIZATION
-------
tag2 count :  160
tag3 count :  6

Tag :  I-PERSON
-------
tag2 count :  252
tag3 count :  2

Tag :  I-WATERBODIES
-------
tag2 count :  50
tag3 count :  6

Tag :  B-INDIVIDUAL
-------
tag2 count :  1619
tag3 count :  184

Tag :  B-DATE
-------
tag2 count :  224
tag3 count :  11

Tag :  B-COUNT
-------
tag2 count :  955
tag3 count :  171

Tag :  B-IMPLEMENT
-------
tag2 count :  20
tag3 count :  1

Tag :  B-TREATMENT
-------
tag2 count :  27
tag3 count :  1

Tag :  B-MEDIA
-------
tag2 count :  73
tag3 count :  1

Tag :  B-POLITICAL
-------
tag2 count :  59
tag3 count :  8

Tag :  B-PERSON
-------
tag2 count :  235
tag3 count :  12

Tag :  I-ARTIFACT
-------
tag2 count :  61
tag3 count :  2

Tag :  B-HUMAN
-------
tag2 count :  246
tag3 count :  107

Tag :  B-TIME
-------
tag2 count :  29
tag3 count :  2

Tag :  B-LANDSCAPES
-------
tag2 count :  15
tag3 count :  1

Tag :  B-DISEASE
-------
tag2 count :  253
tag3 count :  1

Tag :  B-CINEMA
-------
tag2 count :  25
tag3 count :  9

Tag :  I-CITY
-------
tag2 count :  55
tag3 count :  5

Tag :  I-PLACE
-------
tag2 count :  60
tag3 count :  5

Tag :  I-RELPLACE
-------
tag2 count :  59
tag3 count :  1

Tag :  B-ASSOCIATION
-------
tag2 count :  140
tag3 count :  17

Tag :  B-PERIOD
-------
tag2 count :  291
tag3 count :  3

Tag :  I-NATION
-------
tag2 count :  191
tag3 count :  6

Tag :  B-ARTIFACT
-------
tag2 count :  106
tag3 count :  3

Tag :  I-INDIVIDUAL
-------
tag2 count :  1214
tag3 count :  54

Tag :  I-COUNT
-------
tag2 count :  41
tag3 count :  3

Tag :  I-INSTITUTE
-------
tag2 count :  473
tag3 count :  1

Tag :  I-STATE
-------
tag2 count :  55
tag3 count :  14

Tag :  B-PAINTING
-------
tag2 count :  2
tag3 count :  2

Tag :  I-ASSOCIATION
-------
tag2 count :  211
tag3 count :  17

Tag :  B-EVENT
-------
tag2 count :  202
tag3 count :  7

Tag :  I-TITLE
-------
tag2 count :  13
tag3 count :  71

Tag :  B-NONHUMAN
-------
tag2 count :  70
tag3 count :  10

Tag :  B-METALS
-------
tag2 count :  11
tag3 count :  4

Tag :  B-CELESTIAL
-------
tag2 count :  14
tag3 count :  1

Tag :  B-GOV
-------
tag2 count :  317
tag3 count :  5

Tag :  B-INSTITUTE
-------
tag2 count :  225
tag3 count :  1

Tag :  B-CITY
-------
tag2 count :  340
tag3 count :  116

Tag :  B-PVT
-------
tag2 count :  139
tag3 count :  5

Tag :  I-MEDIA
-------
tag2 count :  53
tag3 count :  1

Tag :  B-MONEY
-------
tag2 count :  116
tag3 count :  1

Tag :  B-NATION
-------
tag2 count :  730
tag3 count :  68

Tag :  o
-------
tag2 count :  72396
tag3 count :  84855

Tag :  B-PLACE
-------
tag2 count :  194
tag3 count :  26

Tag :  B-ORGANIZATION
-------
tag2 count :  137
tag3 count :  4

Tag :  I-GOV
-------
tag2 count :  361
tag3 count :  4

Tag :  B-RELIGION
-------
tag2 count :  28
tag3 count :  1

Tag :  B-RELPLACE
-------
tag2 count :  45
tag3 count :  1

Tag :  I-FACILITIES
-------
tag2 count :  28
tag3 count :  2

Tag :  I-HUMAN
-------
tag2 count :  19
tag3 count :  10

Tag :  B-DAY
-------
tag2 count :  11
tag3 count :  1

Tag :  I-PAINTING
-------
tag2 count :  2
tag3 count :  1

Tag :  B-MONTH
-------
tag2 count :  74
tag3 count :  220

Tag :  B-STATE
-------
tag2 count :  115
tag3 count :  36

Tag :  B-CONTINENT
-------
tag2 count :  29
tag3 count :  9

Tag :  B-LOCATION
-------
tag2 count :  15
tag3 count :  4

Tag :  B-GROUP
-------
tag2 count :  238
tag3 count :  2

Tag :  B-FACILITIES
-------
tag2 count :  17
tag3 count :  1

Tag :  B-YEAR
-------
tag2 count :  535
tag3 count :  214

Tag :  B-WATERBODIES
-------
tag2 count :  58
tag3 count :  6

Tag :  I-PVT
-------
tag2 count :  137
tag3 count :  4

Tag :  I-EVENT
-------
tag2 count :  259
tag3 count :  3

Tag :  I-DATE
-------
tag2 count :  353
tag3 count :  16

In [0]:
data[(data['tag3'] == 'B-CITY') & (data['tag2'] not in ['B-INSTITUTE', 'I-INSTITUTE'])]

ValueError: ignored